//! Everything that differs between macOS, Windows, and Linux.
//!
//! Each OS module provides the same items:
//!
//! - `FILE_MANAGER`: name used in "Show in …" labels.
//! - `PACKAGE_EXTENSIONS`: folder extensions the OS shows as one file; the
//!   file index lists such a folder but not its contents.
//! - `RECURSIVE_WATCH`: whether watching a folder also watches its subfolders.
//! - `TEMPLATE_TRAY_ICON`: the OS tints a black tray icon (macOS menu bar).
//! - `prepare_app(app)`: app-wide setup at startup, such as the Dock policy.
//! - `is_reopen(event)`: the user opened the running app again, and the OS
//!   sent an event instead of starting a second process.
//! - `restrict_to_owner(path)`: make a file readable only by the user.
//! - `HIDDEN`: the OS's check for a hidden file or folder besides a name
//!   that starts with a dot (the Windows hidden attribute, the macOS hidden
//!   flag), or `None` when it has none, so the scan reads no metadata.
//! - `NATIVE_ICONS`: whether `app_icon` returns images.
//! - `SELF_UPDATE`: whether an installed copy can replace itself with a new
//!   version (not on Linux, where installing a .deb needs root).
//! - `RICH_CLIPBOARD`: whether clipboard history can save images and copied
//!   files; `read_clipboard` ignores both settings when it cannot.
//! - `app_folders()`: folders to watch for installed or removed apps.
//! - `discover_apps()`: installed apps.
//! - `launch_app(path)`: start an app found by `discover_apps`.
//! - `app_icon(path, pixels)`: PNG bytes of a file's system icon.
//! - `run_system_command(command)`.
//! - `disk_space(path)`: the [`Volume`] that holds `path`.
//! - `clipboard_change()`: a counter that changes with the clipboard content.
//! - `read_clipboard(images, files)`: the content for the latest change, or
//!   `None` when its source marked it secret or it cannot be read.
//! - `exclude_from_history(set)`: mark a copy secret for clipboard managers.
//! - `watch_clipboard(capturing)`: start change notifications; call on the
//!   main thread. `capturing` says whether history is on, so nothing is read
//!   while it is off.
//! - `prepare_launcher(window)`: native window tweaks; call on the main thread.
//! - `place_launcher(app, window, saved)`: move the launcher to `saved` when
//!   that spot is still on a screen, else to the center of the screen with
//!   the pointer.
//! - `launcher_position(window)`: where the launcher is now, in the units
//!   `place_launcher` takes.
//! - `remember_frontmost_app()` / `restore_frontmost_app()`: return focus after Escape.

#[cfg(target_os = "linux")]
mod linux;
#[cfg(target_os = "macos")]
mod macos;
#[cfg(target_os = "windows")]
mod windows;

#[cfg(target_os = "linux")]
pub use linux::*;
#[cfg(target_os = "macos")]
pub use macos::*;
#[cfg(target_os = "windows")]
pub use windows::*;

use crate::error::{Error, Result};
#[cfg(not(target_os = "linux"))]
use crate::features::clipboard::{Content, MAX_IMAGE_BYTES, MAX_IMAGE_PIXELS};
#[cfg(not(target_os = "macos"))]
use crate::settings::LauncherPosition;

/// A disk, as the file manager shows it.
pub struct Volume {
    /// Its name: the Finder name on macOS, the drive on Windows (`C:`), the
    /// mount point on Linux (`/`).
    pub name: String,
    pub total_bytes: u64,
    /// Space left to fill. On macOS this counts purgeable space, as Finder does.
    pub free_bytes: u64,
}

/// Clipboard formats that password managers set to ask history tools to skip
/// a copy. See <http://nspasteboard.org> and the Windows clipboard docs.
pub const SECRET_FORMATS: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "com.apple.is-sensitive",
    "ExcludeClipboardContentFromMonitorProcessing",
    "Clipboard Viewer Ignore",
    "x-kde-passwordManagerHint",
];

/// Move the launcher to `saved` when the middle of its top edge would be on
/// a screen, so it can still be dragged; else center it in the work area of
/// the monitor under the pointer. Every value here is in physical pixels,
/// which Windows and X11 use consistently across monitors.
#[cfg(not(target_os = "macos"))]
fn place_in_physical_pixels(
    app: &tauri::AppHandle,
    window: &tauri::WebviewWindow,
    saved: Option<LauncherPosition>,
) -> tauri::Result<()> {
    let size = window.outer_size()?;
    if let Some(saved) = saved
        && app
            .monitor_from_point(saved.x + f64::from(size.width) / 2.0, saved.y + 1.0)?
            .is_some()
    {
        // `as` saturates, and the check above keeps the spot on a screen.
        return window.set_position(tauri::PhysicalPosition::new(saved.x as i32, saved.y as i32));
    }
    let cursor = app.cursor_position()?;
    let Some(monitor) = app.monitor_from_point(cursor.x, cursor.y)? else {
        return Ok(());
    };
    let area = monitor.work_area();
    let free_width = i64::from(area.size.width.saturating_sub(size.width));
    let free_height = i64::from(area.size.height.saturating_sub(size.height));
    // The window has a fixed height and never grows, so it sits in the
    // exact center rather than high up, as launchers that grow do.
    let x = i64::from(area.position.x) + free_width / 2;
    let y = i64::from(area.position.y) + free_height / 2;
    window.set_position(tauri::PhysicalPosition::new(
        i32::try_from(x).unwrap_or(area.position.x),
        i32::try_from(y).unwrap_or(area.position.y),
    ))
}

#[cfg(not(target_os = "macos"))]
fn physical_position(window: &tauri::WebviewWindow) -> tauri::Result<LauncherPosition> {
    let position = window.outer_position()?;
    Ok(LauncherPosition {
        x: position.x.into(),
        y: position.y.into(),
    })
}

/// Held while reading the clipboard. AppKit's pasteboard is not safe to
/// read from two threads at once, and Windows lets one thread open the
/// clipboard at a time.
#[cfg(not(target_os = "linux"))]
static CLIPBOARD_READ: std::sync::Mutex<()> = std::sync::Mutex::new(());

#[cfg(not(target_os = "linux"))]
fn one_clipboard_reader() -> std::sync::MutexGuard<'static, ()> {
    CLIPBOARD_READ.lock().unwrap_or_else(|e| e.into_inner())
}

#[cfg(not(target_os = "linux"))]
/// Read what the clipboard holds, in the order apps expect: copied files
/// first (Finder also offers their names as text), then text, then images.
/// Kinds the user did not opt into are skipped, not saved as text.
fn read_with_arboard(images: bool, files: bool) -> Option<Content> {
    let mut reader = arboard::Clipboard::new()
        .inspect_err(|error| tracing::warn!(%error, "Cannot read the clipboard"))
        .ok()?;
    if let Ok(paths) = reader.get().file_list()
        && !paths.is_empty()
    {
        return files.then_some(Content::Files(paths));
    }
    if let Ok(text) = reader.get_text() {
        return Some(Content::Text(text));
    }
    if !images {
        return None;
    }
    let image = reader.get_image().ok()?;
    let (width, height) = (
        u32::try_from(image.width).ok()?,
        u32::try_from(image.height).ok()?,
    );
    if u64::from(width) * u64::from(height) > MAX_IMAGE_PIXELS {
        return None;
    }
    let buffer = image::RgbaImage::from_raw(width, height, image.bytes.into_owned())?;
    let mut png = Vec::new();
    buffer
        .write_to(&mut std::io::Cursor::new(&mut png), image::ImageFormat::Png)
        .ok()?;
    (png.len() <= MAX_IMAGE_BYTES).then_some(Content::Image { png, width, height })
}

/// Start a GUI program and return at once; it keeps running on its own.
#[cfg(target_os = "linux")]
fn launch(program: &str) -> Result<()> {
    let mut child = std::process::Command::new(program)
        .spawn()
        .map_err(|error| Error::msg(format!("Could not open {program}: {error}")))?;
    // Reap it when it exits, so no zombie process stays behind.
    std::thread::spawn(move || child.wait());
    Ok(())
}

/// Run a helper program with fixed arguments. Never pass user text here.
fn run(program: &str, args: &[&str]) -> Result<()> {
    let mut command = std::process::Command::new(program);
    command.args(args);
    #[cfg(windows)]
    {
        use std::os::windows::process::CommandExt;
        const CREATE_NO_WINDOW: u32 = 0x0800_0000;
        command.creation_flags(CREATE_NO_WINDOW);
    }
    let output = command
        .output()
        .map_err(|error| Error::msg(format!("Could not run {program}: {error}")))?;
    if output.status.success() {
        return Ok(());
    }
    let detail = String::from_utf8_lossy(&output.stderr);
    Err(Error::msg(format!("{program} failed: {}", detail.trim())))
}

#[cfg(test)]
mod tests {
    #[test]
    fn many_threads_can_read_the_clipboard_at_once() {
        // AppKit crashes on unguarded parallel pasteboard reads.
        std::thread::scope(|scope| {
            for _ in 0..8 {
                scope.spawn(|| {
                    for _ in 0..20 {
                        super::clipboard_change();
                        super::read_clipboard(false, false);
                    }
                });
            }
        });
    }
}
