//! Everything that differs between macOS, Windows, and Linux.
//!
//! Each OS module provides the same items:
//!
//! - `FILE_MANAGER`: name used in "Show in …" labels.
//! - `NATIVE_ICONS`: whether `app_icon` returns images.
//! - `app_folders()`: folders to watch for installed or removed apps.
//! - `discover_apps()`: installed apps.
//! - `launch_app(path)`: start an app found by `discover_apps`.
//! - `app_icon(path, pixels)`: PNG bytes of a file's system icon.
//! - `run_system_command(command)`.
//! - `clipboard_change()`: a counter that changes with the clipboard content.
//! - `clipboard_is_concealed()`: the source marked the content secret.
//! - `watch_clipboard()`: start change notifications; call on the main thread.
//! - `prepare_launcher(window)`: native window tweaks; call on the main thread.
//! - `remember_frontmost_app()` / `restore_frontmost_app()`: return focus after Escape.

#[cfg(target_os = "linux")]
mod linux;
#[cfg(target_os = "macos")]
mod macos;
#[cfg(target_os = "windows")]
mod windows;

#[cfg(target_os = "linux")]
pub use linux::*;
#[cfg(target_os = "macos")]
pub use macos::*;
#[cfg(target_os = "windows")]
pub use windows::*;

use crate::error::{Error, Result};

/// Clipboard formats that password managers set to ask history tools to skip
/// a copy. See <http://nspasteboard.org> and the Windows clipboard docs.
pub const SECRET_FORMATS: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "com.apple.is-sensitive",
    "ExcludeClipboardContentFromMonitorProcessing",
    "Clipboard Viewer Ignore",
    "x-kde-passwordManagerHint",
];

/// Run a helper program with fixed arguments. Never pass user text here.
fn run(program: &str, args: &[&str]) -> Result<()> {
    let mut command = std::process::Command::new(program);
    command.args(args);
    #[cfg(windows)]
    {
        use std::os::windows::process::CommandExt;
        const CREATE_NO_WINDOW: u32 = 0x0800_0000;
        command.creation_flags(CREATE_NO_WINDOW);
    }
    let output = command
        .output()
        .map_err(|error| Error::msg(format!("Could not run {program}: {error}")))?;
    if output.status.success() {
        return Ok(());
    }
    let detail = String::from_utf8_lossy(&output.stderr);
    Err(Error::msg(format!("{program} failed: {}", detail.trim())))
}
