// Generated by serialized_ipc_contracts_match_frontend_fixture. Do not edit.
import type { ContractFixture } from "../ipc-contract";

export const contracts = {
  "actions": [
    "launch",
    "open",
    "reveal",
    "copy",
    "delete",
    "run",
    "regenerate"
  ],
  "clipboard": {
    "content": "Example",
    "createdAt": 1,
    "id": 42,
    "lastUsedAt": null
  },
  "defaults": {
    "appPreferences": {},
    "categoryShortcuts": [],
    "clearQueryOnOpen": true,
    "clipboardHistoryDecided": true,
    "clipboardHistoryEnabled": true,
    "clipboardHistoryLimit": 100,
    "currencyRatesEnabled": true,
    "fileSearchExcludedDirs": [
      "node_modules",
      "target"
    ],
    "fileSearchLimit": 50000,
    "fileSearchRoots": null,
    "fileWatchEnabled": true,
    "hideOnBlur": true,
    "shortcut": "Control+Shift+Space",
    "startAtLogin": false,
    "visibleCategories": [
      "all",
      "apps",
      "files",
      "clipboard",
      "calculator",
      "system",
      "emoji",
      "password",
      "timezone",
      "url",
      "web"
    ],
    "webSearches": []
  },
  "details": [
    {
      "entropyBits": 128,
      "strength": "Strong",
      "type": "password",
      "variant": "password"
    },
    {
      "ambiguous": false,
      "local": "17:00",
      "source": "10:00",
      "sourceZone": "UTC",
      "type": "timezone"
    },
    {
      "ambiguous": true,
      "local": "17:00",
      "source": "10:00",
      "sourceZone": "UTC",
      "targetZone": "Asia/Bangkok",
      "type": "timezone"
    },
    {
      "basedOn": "2026-09-28",
      "expression": "tomorrow",
      "result": "2026-09-29",
      "type": "dateCalculation"
    },
    {
      "original": "https://example.com/?utm_source=test",
      "removed": 1,
      "type": "cleanedUrl"
    },
    {
      "engine": "Example",
      "query": "hello world",
      "type": "webSearch",
      "url": "https://example.com/?q=hello%20world"
    }
  ],
  "fullResult": {
    "confirmation": {
      "confirmLabel": "Restart",
      "description": "Unsaved work can be lost.",
      "title": "Restart?"
    },
    "detail": {
      "entropyBits": 128,
      "strength": "Strong",
      "type": "password",
      "variant": "password"
    },
    "icon": "data:image/png;base64,example",
    "id": "full",
    "kind": "systemCommand",
    "path": "/example/file",
    "pin": {
      "categories": [
        "all",
        "apps",
        "files",
        "emoji",
        "calculator",
        "clipboard",
        "system",
        "password",
        "timezone",
        "url",
        "web"
      ],
      "key": "system:restart"
    },
    "primaryAction": "run",
    "score": 100,
    "secondaryActions": [
      "launch",
      "open",
      "reveal",
      "copy",
      "delete",
      "run",
      "regenerate"
    ],
    "subtitle": "Confirmation required",
    "title": "Restart"
  },
  "imported": {
    "appearance": "dark",
    "compact": true,
    "followSystemGlass": null,
    "ignoredKeys": [
      "futureKey"
    ],
    "settings": {
      "appPreferences": {},
      "categoryShortcuts": [],
      "clearQueryOnOpen": true,
      "clipboardHistoryDecided": true,
      "clipboardHistoryEnabled": true,
      "clipboardHistoryLimit": 100,
      "currencyRatesEnabled": true,
      "fileSearchExcludedDirs": [
        "node_modules",
        "target"
      ],
      "fileSearchLimit": 50000,
      "fileSearchRoots": null,
      "fileWatchEnabled": true,
      "hideOnBlur": true,
      "shortcut": "Control+Shift+Space",
      "startAtLogin": false,
      "visibleCategories": [
        "all",
        "apps",
        "files",
        "clipboard",
        "calculator",
        "system",
        "emoji",
        "password",
        "timezone",
        "url",
        "web"
      ],
      "webSearches": []
    }
  },
  "launcher": {
    "initialMode": "apps",
    "platform": "linux",
    "settings": {
      "appPreferences": {},
      "categoryShortcuts": [],
      "clearQueryOnOpen": true,
      "clipboardHistoryDecided": true,
      "clipboardHistoryEnabled": true,
      "clipboardHistoryLimit": 100,
      "currencyRatesEnabled": true,
      "fileSearchExcludedDirs": [
        "node_modules",
        "target"
      ],
      "fileSearchLimit": 50000,
      "fileSearchRoots": null,
      "fileWatchEnabled": true,
      "hideOnBlur": true,
      "shortcut": "Control+Shift+Space",
      "startAtLogin": false,
      "visibleCategories": [
        "all",
        "apps",
        "files",
        "clipboard",
        "calculator",
        "system",
        "emoji",
        "password",
        "timezone",
        "url",
        "web"
      ],
      "webSearches": []
    },
    "visible": true,
    "warnings": [
      {
        "code": "settingsRead",
        "message": "Fixture warning",
        "retryable": false
      },
      {
        "code": "shortcutRegistration",
        "message": "Fixture warning",
        "retryable": false
      },
      {
        "code": "shortcutsUnavailable",
        "message": "Fixture warning",
        "retryable": false
      },
      {
        "code": "clipboardLimited",
        "message": "Fixture warning",
        "retryable": false
      },
      {
        "code": "trayUnavailable",
        "message": "Fixture warning",
        "retryable": false
      },
      {
        "code": "storageUnavailable",
        "message": "Fixture warning",
        "retryable": false
      },
      {
        "code": "clipboardUnavailable",
        "message": "Fixture warning",
        "retryable": false
      }
    ]
  },
  "modes": [
    "all",
    "apps",
    "files",
    "emoji",
    "calculator",
    "clipboard",
    "system",
    "password",
    "timezone",
    "url",
    "web"
  ],
  "response": {
    "currency": {
      "asOf": null,
      "refreshing": false,
      "warning": null
    },
    "files": {
      "indexing": false,
      "total": 3,
      "warning": null
    },
    "indexError": null,
    "indexing": false,
    "notice": null,
    "preferredSelectionId": null,
    "results": [
      {
        "icon": null,
        "id": "result:0",
        "kind": "app",
        "primaryAction": "copy",
        "score": 10,
        "secondaryActions": [],
        "subtitle": "Wire example",
        "title": "Fixture"
      },
      {
        "icon": null,
        "id": "result:1",
        "kind": "file",
        "primaryAction": "copy",
        "score": 10,
        "secondaryActions": [],
        "subtitle": "Wire example",
        "title": "Fixture"
      },
      {
        "icon": null,
        "id": "result:2",
        "kind": "folder",
        "primaryAction": "copy",
        "score": 10,
        "secondaryActions": [],
        "subtitle": "Wire example",
        "title": "Fixture"
      },
      {
        "icon": null,
        "id": "result:3",
        "kind": "calculation",
        "primaryAction": "copy",
        "score": 10,
        "secondaryActions": [],
        "subtitle": "Wire example",
        "title": "Fixture"
      },
      {
        "icon": null,
        "id": "result:4",
        "kind": "emoji",
        "primaryAction": "copy",
        "score": 10,
        "secondaryActions": [],
        "subtitle": "Wire example",
        "title": "Fixture"
      },
      {
        "icon": null,
        "id": "result:5",
        "kind": "clipboard",
        "primaryAction": "copy",
        "score": 10,
        "secondaryActions": [],
        "subtitle": "Wire example",
        "title": "Fixture"
      },
      {
        "icon": null,
        "id": "result:6",
        "kind": "systemCommand",
        "primaryAction": "copy",
        "score": 10,
        "secondaryActions": [],
        "subtitle": "Wire example",
        "title": "Fixture"
      },
      {
        "icon": null,
        "id": "result:7",
        "kind": "password",
        "primaryAction": "copy",
        "score": 10,
        "secondaryActions": [],
        "subtitle": "Wire example",
        "title": "Fixture"
      },
      {
        "icon": null,
        "id": "result:8",
        "kind": "timezone",
        "primaryAction": "copy",
        "score": 10,
        "secondaryActions": [],
        "subtitle": "Wire example",
        "title": "Fixture"
      },
      {
        "icon": null,
        "id": "result:9",
        "kind": "cleanedUrl",
        "primaryAction": "copy",
        "score": 10,
        "secondaryActions": [],
        "subtitle": "Wire example",
        "title": "Fixture"
      },
      {
        "icon": null,
        "id": "result:10",
        "kind": "webSearch",
        "primaryAction": "copy",
        "score": 10,
        "secondaryActions": [],
        "subtitle": "Wire example",
        "title": "Fixture"
      }
    ],
    "storageError": null,
    "total": 11
  },
  "settings": {
    "appPreferences": {
      "app:example": {
        "aliases": [
          "editor"
        ],
        "hidden": true
      }
    },
    "categoryShortcuts": [
      {
        "mode": "apps",
        "shortcut": "Control+Shift+KeyA"
      }
    ],
    "clearQueryOnOpen": true,
    "clipboardHistoryDecided": true,
    "clipboardHistoryEnabled": true,
    "clipboardHistoryLimit": 100,
    "currencyRatesEnabled": true,
    "fileSearchExcludedDirs": [
      "node_modules",
      "target"
    ],
    "fileSearchLimit": 50000,
    "fileSearchRoots": [
      "/example"
    ],
    "fileWatchEnabled": true,
    "hideOnBlur": true,
    "shortcut": "Control+Shift+Space",
    "startAtLogin": false,
    "visibleCategories": [
      "all",
      "apps",
      "files",
      "clipboard",
      "calculator",
      "system",
      "emoji",
      "password",
      "timezone",
      "url",
      "web"
    ],
    "webSearches": [
      {
        "enabled": true,
        "keyword": "ex",
        "name": "Example",
        "template": "https://example.com/?q={query}"
      }
    ]
  },
  "settingsInfo": {
    "configPath": "/example/settings.json",
    "dataPath": "/example/tinydash.sqlite3",
    "defaults": {
      "appPreferences": {},
      "categoryShortcuts": [],
      "clearQueryOnOpen": true,
      "clipboardHistoryDecided": true,
      "clipboardHistoryEnabled": true,
      "clipboardHistoryLimit": 100,
      "currencyRatesEnabled": true,
      "fileSearchExcludedDirs": [
        "node_modules",
        "target"
      ],
      "fileSearchLimit": 50000,
      "fileSearchRoots": null,
      "fileWatchEnabled": true,
      "hideOnBlur": true,
      "shortcut": "Control+Shift+Space",
      "startAtLogin": false,
      "visibleCategories": [
        "all",
        "apps",
        "files",
        "clipboard",
        "calculator",
        "system",
        "emoji",
        "password",
        "timezone",
        "url",
        "web"
      ],
      "webSearches": []
    },
    "platform": "linux",
    "settings": {
      "appPreferences": {},
      "categoryShortcuts": [],
      "clearQueryOnOpen": true,
      "clipboardHistoryDecided": true,
      "clipboardHistoryEnabled": true,
      "clipboardHistoryLimit": 100,
      "currencyRatesEnabled": true,
      "fileSearchExcludedDirs": [
        "node_modules",
        "target"
      ],
      "fileSearchLimit": 50000,
      "fileSearchRoots": null,
      "fileWatchEnabled": true,
      "hideOnBlur": true,
      "shortcut": "Control+Shift+Space",
      "startAtLogin": false,
      "visibleCategories": [
        "all",
        "apps",
        "files",
        "clipboard",
        "calculator",
        "system",
        "emoji",
        "password",
        "timezone",
        "url",
        "web"
      ],
      "webSearches": []
    },
    "shortcutsAvailable": true,
    "version": "0.1.3"
  },
  "update": {
    "available": true,
    "message": "Update available",
    "notes": null,
    "version": "0.2.0"
  },
  "warningResponse": {
    "currency": {
      "asOf": "2026-09-28",
      "refreshing": true,
      "warning": "Rates are old"
    },
    "files": {
      "indexing": true,
      "total": 1,
      "warning": "Scan incomplete"
    },
    "indexError": "Index unavailable",
    "indexing": true,
    "notice": "Try a shorter query",
    "preferredSelectionId": "clipboard:1",
    "results": [],
    "storageError": {
      "code": "storageUnavailable",
      "message": "Storage unavailable",
      "retryable": false
    },
    "total": 0
  }
} satisfies ContractFixture;
