// Generated by generated_ipc_wire_types_match_frontend. Do not edit.
export type Action = "launch" | "open" | "reveal" | "copy" | "delete" | "run" | "regenerate";
export type ActionConfirmation = { title: string, description: string, confirmLabel: string, };
export type AppPreference = { aliases: Array<string>, hidden: boolean, };
export type AppearanceChange = { "kind": "appearance", "value": LauncherAppearance } | { "kind": "compact", "value": boolean } | { "kind": "systemGlass", "value": boolean };
export type CategoryShortcut = { mode: SearchMode, shortcut: string, };
export type ClipboardEntry = { id: number, content: string, createdAt: number, lastUsedAt: number | null, };
export type CurrencyStatus = { asOf: string | null, refreshing: boolean, warning: string | null, };
export type FileStatus = { total: number, indexing: boolean, warning: string | null, };
export type LauncherAppearance = "light" | "dark" | "sage" | "rose" | "ink";
export type LauncherInfo = { settings: Settings, platform: string, warnings: Array<LauncherWarning>, visible: boolean, initialMode: SearchMode | null, };
export type LauncherWarning = { code: WarningCode, message: string, 
/**
 * Whether repeating the originating operation can recover without restart
 * or configuration repair. This is metadata, not an instruction to retry.
 */
retryable: boolean, };
export type ResultKind = "app" | "file" | "folder" | "calculation" | "emoji" | "clipboard" | "systemCommand" | "password" | "timezone" | "cleanedUrl" | "webSearch";
export type ResultPin = { key: string, categories: Array<SearchMode>, };
export type SearchMode = "all" | "apps" | "files" | "emoji" | "calculator" | "clipboard" | "system" | "password" | "timezone" | "url" | "web";
export type SearchResponse = { preferredSelectionId: string | null, results: Array<SearchResult>, total: number, indexing: boolean, indexError: string | null, notice: string | null, storageError: LauncherWarning | null, files: FileStatus, currency: CurrencyStatus, };
export type SearchResult = { id: string, kind: ResultKind, title: string, subtitle: string, path?: string, score: number, icon: string | null, primaryAction: Action, secondaryActions: Array<Action>, pin?: ResultPin, confirmation?: ActionConfirmation, detail?: ToolDetail, };
export type Settings = { clearQueryOnOpen: boolean, hideOnBlur: boolean, shortcut: string, categoryShortcuts: Array<CategoryShortcut>, startAtLogin: boolean, appPreferences: { [key in string]: AppPreference }, webSearches: Array<WebSearch>, clipboardHistoryEnabled: boolean, clipboardHistoryDecided: boolean, clipboardHistoryLimit: number, fileSearchRoots: Array<string> | null, fileSearchLimit: number, fileSearchExcludedDirs: Array<string>, fileWatchEnabled: boolean, currencyRatesEnabled: boolean, visibleCategories: Array<SearchMode>, };
export type SettingsImport = { settings: Settings, ignoredKeys: Array<string>, appearance: string | null, compact: boolean | null, followSystemGlass: boolean | null, };
export type SettingsInfo = { settings: Settings, defaults: Settings, platform: string, version: string, configPath: string, dataPath: string, shortcutsAvailable: boolean, };
export type ToolDetail = { "type": "password", variant: string, entropyBits: number, strength: string, } | { "type": "timezone", source: string, local: string, sourceZone: string, targetZone?: string, ambiguous: boolean, } | { "type": "dateCalculation", expression: string, basedOn: string, result: string, } | { "type": "cleanedUrl", original: string, removed: number, } | { "type": "webSearch", engine: string, query: string, url: string, };
export type UpdateStatus = { available: boolean, version: string | null, notes: string | null, message: string, };
export type WarningCode = "settingsRead" | "shortcutRegistration" | "shortcutsUnavailable" | "clipboardLimited" | "trayUnavailable" | "storageUnavailable" | "clipboardUnavailable";
export type WebSearch = { name: string, keyword: string, template: string, enabled: boolean, };
export type Commands = {
  app_catalog: { args: []; result: Array<SearchResult> };
  cancel_search: { args: [request_id: number]; result: void };
  check_update: { args: []; result: UpdateStatus };
  choose_clipboard_history: { args: [enabled: boolean]; result: Settings };
  clear_clipboard_history: { args: [keep_pinned: boolean | null]; result: void };
  clipboard_preview: { args: [id: string]; result: ClipboardEntry };
  copy_clipboard_selection: { args: [ids: Array<string>, separator: string]; result: void };
  edit_clipboard_history: { args: [id: string, text: string]; result: void };
  execute_action: { args: [id: string, action: Action, confirmed: boolean | null]; result: void };
  export_settings: { args: [appearance: string, compact: boolean, follow_system_glass: boolean]; result: boolean };
  get_settings: { args: []; result: SettingsInfo };
  hide_launcher: { args: []; result: void };
  install_update: { args: []; result: void };
  launcher_ready: { args: []; result: LauncherInfo };
  open_settings: { args: []; result: void };
  preview_settings_import: { args: []; result: SettingsImport | null };
  preview_web_search: { args: [search: WebSearch, query: string]; result: string };
  quit_app: { args: []; result: void };
  refresh_apps: { args: []; result: void };
  refresh_currency: { args: []; result: void };
  refresh_files: { args: []; result: void };
  reset_launcher_position: { args: []; result: void };
  reveal_backup: { args: []; result: void };
  reveal_settings_path: { args: [data: boolean]; result: void };
  save_clipboard_file: { args: [id: string]; result: boolean };
  save_settings: { args: [settings: Settings]; result: Settings };
  search: { args: [query: string, mode: SearchMode, request_id: number | null]; result: SearchResponse };
  set_app_preference: { args: [id: string, aliases: Array<string>, hidden: boolean]; result: Settings };
  set_launcher_appearance: { args: [appearance: LauncherAppearance]; result: boolean };
  set_pinned: { args: [id: string, category: SearchMode, pinned: boolean]; result: void };
  set_shortcut_recording: { args: [recording: boolean]; result: void };
  sync_appearance: { args: [change: AppearanceChange]; result: void };
};
export const commandArguments = {"app_catalog":[],"cancel_search":[["request_id","number"]],"check_update":[],"choose_clipboard_history":[["enabled","boolean"]],"clear_clipboard_history":[["keep_pinned","boolean | null"]],"clipboard_preview":[["id","string"]],"copy_clipboard_selection":[["ids","Array<string>"],["separator","string"]],"edit_clipboard_history":[["id","string"],["text","string"]],"execute_action":[["id","string"],["action","Action"],["confirmed","boolean | null"]],"export_settings":[["appearance","string"],["compact","boolean"],["follow_system_glass","boolean"]],"get_settings":[],"hide_launcher":[],"install_update":[],"launcher_ready":[],"open_settings":[],"preview_settings_import":[],"preview_web_search":[["search","WebSearch"],["query","string"]],"quit_app":[],"refresh_apps":[],"refresh_currency":[],"refresh_files":[],"reset_launcher_position":[],"reveal_backup":[],"reveal_settings_path":[["data","boolean"]],"save_clipboard_file":[["id","string"]],"save_settings":[["settings","Settings"]],"search":[["query","string"],["mode","SearchMode"],["request_id","number | null"]],"set_app_preference":[["id","string"],["aliases","Array<string>"],["hidden","boolean"]],"set_launcher_appearance":[["appearance","LauncherAppearance"]],"set_pinned":[["id","string"],["category","SearchMode"],["pinned","boolean"]],"set_shortcut_recording":[["recording","boolean"]],"sync_appearance":[["change","AppearanceChange"]]} as const;
