pub(super) fn app_description(bundle_id: Option<&str>, category: Option<&str>) -> &'static str {
    // Bundles provide a category, but usually no short description. Use bundle
    // identifiers so these labels also work with renamed or localized apps.
    let known = match bundle_id.unwrap_or_default() {
        "com.apple.Safari" | "com.google.Chrome" | "org.mozilla.firefox" => Some("Web browser"),
        "com.apple.finder" => Some("Files and folders"),
        "com.apple.Notes" => Some("Notes and checklists"),
        "com.apple.iCal" => Some("Events and reminders"),
        "com.mitchellh.ghostty" | "com.apple.Terminal" => Some("Terminal emulator"),
        "com.apple.systempreferences" => Some("System preferences"),
        "com.apple.ActivityMonitor" => Some("System activity"),
        "com.apple.airport.airportutility" => Some("Wireless network settings"),
        "com.google.android.studio" => Some("Android development"),
        "com.apple.AppStore" => Some("App downloads and updates"),
        "com.larksuite.larkApp" => Some("Team chat and collaboration"),
        "com.microsoft.VSCode" => Some("Code editor"),
        "com.apple.dt.Xcode" => Some("App development"),
        "com.apple.mail" => Some("Email"),
        "com.apple.MobileSMS" => Some("Messages and conversations"),
        "com.apple.FaceTime" => Some("Voice and video calls"),
        "com.apple.Preview" => Some("Images and PDF documents"),
        "com.apple.Photos" => Some("Photo library"),
        "com.apple.Music" => Some("Music library and player"),
        "com.apple.reminders" => Some("Tasks and reminders"),
        "com.apple.calculator" => Some("Calculations and conversions"),
        "com.apple.DiskUtility" => Some("Disk management"),
        _ => None,
    };
    known.unwrap_or_else(|| match category.unwrap_or_default() {
        "public.app-category.business" => "Business",
        "public.app-category.developer-tools" => "Developer tools",
        "public.app-category.education" => "Education",
        "public.app-category.entertainment" => "Entertainment",
        "public.app-category.finance" => "Finance",
        "public.app-category.games" => "Games",
        "public.app-category.graphics-design" => "Graphics and design",
        "public.app-category.healthcare-fitness" => "Health and fitness",
        "public.app-category.lifestyle" => "Lifestyle",
        "public.app-category.medical" => "Medical",
        "public.app-category.music" => "Music",
        "public.app-category.news" => "News",
        "public.app-category.photography" => "Photography",
        "public.app-category.productivity" => "Productivity",
        "public.app-category.reference" => "Reference",
        "public.app-category.social-networking" => "Social networking",
        "public.app-category.sports" => "Sports",
        "public.app-category.travel" => "Travel",
        "public.app-category.utilities" => "Utilities",
        "public.app-category.video" => "Video",
        "public.app-category.weather" => "Weather",
        _ => "Application",
    })
}
